apiVersion: v1
kind: Service
metadata:
  name: patients
  labels:
    app: patients
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080    
  selector:
    app: patients
  type: ClusterIP
