apiVersion: apps/v1
kind: Deployment
metadata:
  name: patients

spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: patients
        image: docker.io/kamranazeem/patients
        envFrom:
        - configMapRef:
            name: patients
        ports:
        - containerPort: 4444
        resources:
          requests:
            cpu: "5m"
            memory: "16Mi"
          limits:
            cpu: "10m"
            memory: "32Mi"
